[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"